modLoader="javafml"
loaderVersion="[47,)"
license="GPLv3"

[[mods]]
modId="cbcmoreshells"
version="0.0.15-1.20.1"
displayName="Create Big Cannons More Shells"
displayURL="https://www.curseforge.com/minecraft/mc-mods/"
logoFile=""
credits=""
authors="cainiao1053"
description='''
Shells...
'''

[[dependencies.cbcmoreshells]] #optional
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="AFTER"
side="SERVER"

[[dependencies.cbcmoreshells]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="AFTER"
side="SERVER"

[[dependencies.cbcmoreshells]]
modId="create"
mandatory=true
versionRange="[0.5.1.h,)"
ordering="AFTER"
side="BOTH"

[[dependencies.cbcmoreshells]]
modId="createbigcannons"
mandatory=true
versionRange="[5.6.0,)"
ordering="AFTER"
side="BOTH"

